### ISSUE TITLE
match

### ISSUE THREAD

**Issue by Ordinaryhrz** [georg-bn/rotation-steerers#3]
Firstly, thank you for your work. I have a question: the paper introduces several methods for matching. Why were methods like LightGlue and SuperGlue not used in the experiments?

**Comment by Ordinaryhrz** [comment]
I wonder if it's possible

**Comment by georg-bn** [comment]
It would be possible, but the benefits of using steerers diminishes with more costly matching methods. Still, you could use the lightglue for dedode that is in kornia and steer the descriptions with our steerers from "setting A". 

One could also retrain lightglue for our descriptors from settings A and B. I think interesting future work would be creating a learnt matcher like lightglue that is aware of the steerer and perhaps uses it in the intermediate layers.

**Comment by Ordinaryhrz** [comment]
thank you so much

**Comment by guipotje** [comment]
> It would be possible, but the benefits of using steerers diminishes with more costly matching methods. Still, you could use the lightglue for dedode that is in kornia and steer the descriptions with our steerers from "setting A".
> 
> One could also retrain lightglue for our descriptors from settings B and C. I think interesting future work would be creating a learnt matcher like lightglue that is aware of the steerer and perhaps uses it in the intermediate layers.

Hi @georg-bn, I was wondering if it would be possible to apply a steerer right before the final correlation matrix in LightGlue. Intuitively, the token embeddings before the final correlation are no different from an embedding from a local descriptor. By training a projection matrix on these final token embeddings, it should become rotation-equivariant, if I understood correctly?

**Comment by guipotje** [comment]
It makes sense if Lightglue gets confused; nevertheless, it's worth a try to see the outcome. Thanks for replying!

**Comment by noahzn** [comment]
@guipotje  "One could also retrain lightglue for our descriptors from settings B and C". How can I achieve this? I have trained XFeat with a learned steerer, how should I use the descriptors to re-train lightglue?
